###
GET http://localhost:3333/students

###
GET http://localhost:3333/students/cpf/123.456.789-00

###
GET http://localhost:3333/students/1

###
POST http://localhost:3333/students
Content-Type: application/json

{
  "name": "Lucas Pessone",
  "cpf": "12345671900",
  "rg": "123456789" 
}

###
PUT http://localhost:3333/students/1
Content-Type: application/json

{
  "name": "Lucas R. M. Pessone"
}

###
DELETE http://localhost:3333/students/2
